version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"
        environment:
            SA_PASSWORD: "Kuama123"
            ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        volumes:
            - sql_data_volume:/var/opt/mssql
volumes: 
    sql_data_volume:
