version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres:latest
   restart: on-failure
   environment:
     POSTGRES_DB: kerberodb # default db name
     POSTGRES_USER: kuama # db username
     POSTGRES_PASSWORD: kuama # db psw
   ports:
     - "5432:5432"
   volumes:
     - kerbero-data:/var/lib/postgresql/data/

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:latest
   restart: on-failure
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: kuama
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 kerbero-data:
 pgadmin-data:
   